Controllers/BuscaController.cs
using HeathCheck1.Database;
using HeathCheck1.Models;
using HeathCheck1.Repositorios;
using Microsoft.AspNetCore.Mvc;

namespace HeathCheck1.Controllers
{
    public class BuscaController : Controller
    {
        private readonly IEspecialistaRepositorio _especialistaRepositorio;


        private readonly Context _bancocontext;


        public BuscaController(IEspecialistaRepositorio especialistaRepositorio, Context context)
        {
            _especialistaRepositorio = especialistaRepositorio;

            _bancocontext = context;

        }
        public IActionResult BuscaEspecialista()
        {
            
            return View();

            
        }
        public IActionResult TelaEspecialista()
        {

            return View();


        }

        public IActionResult ListarEspecialista(string searchstring)
        {

            var especialista = from m in _bancocontext.especialistas
                               select m;

            if (!String.IsNullOrEmpty(searchstring))
            {
                especialista = especialista.Where(s => s.name.Contains(searchstring));
            }

            return View(especialista);
        }
    }
}

Controllers/EspecialistaController.cs
using HeathCheck1.Database;
using HeathCheck1.Models;
using HeathCheck1.Repositorios;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Calendar.v3;
using Google.Apis.Calendar.v3.Data;
using Google.Apis.Services;
using Google.Apis.Util.Store;

namespace HeathCheck1.Controllers
{
    public class EspecialistaController : Controller
    {
        
        private readonly IEspecialistaRepositorio _especialistaRepositorio;


        private readonly Context _bancocontext;


        public EspecialistaController(IEspecialistaRepositorio especialistaRepositorio, Context context)
        {
            _especialistaRepositorio = especialistaRepositorio;

            _bancocontext = context;

        }

        //GET:EspecialistaController/BuscarEspecialidade
        public ActionResult BuscarEspecialidade()
        {
           List<EspecialidadeModel> especialidade = _especialistaRepositorio.ListarEspecialidade();
            return View(especialidade);
          

        }

        // GET: EspecialistaController/Create
        public ActionResult Salvar()
        {
            ViewBag.especialidades = new SelectList(_bancocontext.especialidades, "id", "nome");
            return View();
        }

        // POST: EspecialistaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Create( EspecialistaModel especialista)
        {

          
            _especialistaRepositorio.SalvarEspecialista(especialista);
            return RedirectToAction("Index","Login");
        }


       
    }
}

Controllers/UsuarioController.cs
using HeathCheck1.Models;
using HeathCheck1.Repositorios;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace HeathCheck1.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;

        public UsuarioController(IUsuarioRepositorio usuarioRepositorio)
        {
            _usuarioRepositorio = usuarioRepositorio;


        }

        // GET: UsuarioController/Create
        public ActionResult Salvar()
        {

            return View();
        }

        // POST: UsuarioController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Salvar(UsuarioModel usuario)
        {

            _usuarioRepositorio.Salvar(usuario);
            return RedirectToAction("Index","Login");
        }

       

   
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HeathCheck</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HeathCheck1.styles.css" asp-append-version="true" /> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-dark bg-dark ">
            <div class="container-fluid">
                <a class="navbar-brand fs-1" asp-area="" asp-controller="Home" asp-action="Index">HeathCheck</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 fs-5">                       
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Busca" asp-action="ListarEspecialista">Especialistas</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-white" >Exames</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Busca" asp-action="BuscaEspecialista">Busca</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-white" >Pergunte a um especialista</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav flex-grow-1 fs-5 justify-content-md-end">  
                         <li class="nav-item dropdown ">
                              <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Cadastre-se
                              </a>
                              <ul class="dropdown-menu dropdown-menu-dark  fs-5" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Especialista" asp-action="Salvar">Especialista</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Consultorio" asp-action="Salvar" >Consultório</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Usuario" asp-action="Salvar" >Usuário</a></li>
                              </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Login" asp-action="Salvar">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="main-wrapper">
        <main role="main" class="container-fluid">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color: black">
        <div class="container" style="color: white; text-align: center;">
            &copy; 2022 - HeathCheck1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutDeslogado.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HeathCheck</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HeathCheck1.styles.css" asp-append-version="true" /> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-dark bg-dark ">
            <div class="container-fluid">
                <a class="navbar-brand fs-1" asp-area="" asp-controller="Login" asp-action="Index">HeathCheck</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 fs-5">                       
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Login" asp-action="Index">Especialistas</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-white" >Exames</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" >Pergunte a um especialista</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav flex-grow-1 fs-5 justify-content-md-end">  
                         <li class="nav-item dropdown ">
                              <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Cadastre-se
                              </a>
                              <ul class="dropdown-menu dropdown-menu-dark  fs-5" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Especialista" asp-action="Salvar">Especialista</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Consultorio" asp-action="Salvar" >Consultório</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Usuario" asp-action="Salvar" >Usuário</a></li>
                              </ul>
                        </li>
                        <li class="nav-item dropdown ">
                              <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Login
                              </a>
                              <ul class="dropdown-menu dropdown-menu-dark  fs-5" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="LoginEspecialista" asp-action="IndexEspecialista">Especialista</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Login" asp-action="Index">Usuario</a></li>
                                 </ul>
                                  </li>
                            </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="main-wrapper">
        <main role="main" class="container-fluid">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color: black">
        <div class="container" style="color: white; text-align: center;">
            &copy; 2022 - HeathCheck1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layoutlogado.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HeathCheck</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HeathCheck1.styles.css" asp-append-version="true" /> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-dark bg-dark ">
            <div class="container-fluid">
              @await Component.InvokeAsync("Menu");
            </div>
        </nav>
    </header>
    <div class="main-wrapper">
        <main role="main" class="container-fluid">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color: black">
        <div class="container" style="color: white; text-align: center;">
            &copy; 2022 - HeathCheck1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutlogadoEspecialista.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Especialista</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HeathCheck1.styles.css" asp-append-version="true" /> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-dark bg-dark ">
            <div class="container-fluid">
              @await Component.InvokeAsync("MenuEspecialista");
            </div>
        </nav>
    </header>
    <div class="main-wrapper">
        <main role="main" class="container-fluid">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color: black">
        <div class="container" style="color: white; text-align: center;">
            &copy; 2022 - HeathCheck1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>