Controllers/AgendamentoController.cs
using Google.Apis.Auth.OAuth2;
using Google.Apis.Calendar.v3;
using Google.Apis.Calendar.v3.Data;
using Google.Apis.Services;
using Google.Apis.Util.Store;
using HeathCheck1.Database;
using HeathCheck1.Models;
using HeathCheck1.Repositorios;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HeathCheck1.Controllers
{
    public class AgendamentoController : Controller
    {

         public class calenderEvent
        {
            public string Summary { get; set; }
            public string Organizer { get; set; }
            public string Description { get; set; }
            public string StartTime { get; set; }
            public string EndTime { get; set; }

        }
        public List<calenderEvent> GoogleEvents = new List<calenderEvent>();
        static string[] Scopes = { CalendarService.Scope.CalendarReadonly };
        static string ApplicationName = "Google Calendar API .NET Quickstart";

       

  


        
        
      
        

        // GET: AgendamentoController/Salvar
        public ActionResult Salvar()
        {

            CallenderEvents();
            ViewBag.EventList = GoogleEvents;

            return View();
        }

        // POST: EspecialistaController/Create
   
        public void CallenderEvents()
        {

            UserCredential credential;
            // Load client secrets.
            using (var stream =
                   new FileStream("credential.json", FileMode.Open, FileAccess.Read))
            {
                /* The file token.json stores the user's access and refresh tokens, and is created
                 automatically when the authorization flow completes for the first time. */
                string credPath = "token.json";
                credential = GoogleWebAuthorizationBroker.AuthorizeAsync(
                    GoogleClientSecrets.FromStream(stream).Secrets,
                    Scopes,
                    "user",
                    CancellationToken.None,
                    new FileDataStore(credPath, true)).Result;

            }

            // Create Google Calendar API service.
            var service = new CalendarService(new BaseClientService.Initializer
            {
                HttpClientInitializer = credential,
                ApplicationName = ApplicationName
            });

            // Define parameters of request.
            EventsResource.ListRequest request = service.Events.List("primary");
            request.TimeMin = DateTime.Now;
            request.ShowDeleted = false;
            request.SingleEvents = true;
            request.MaxResults = 10;
            request.OrderBy = EventsResource.ListRequest.OrderByEnum.StartTime;

            // List events.
            Events events = request.Execute();
            Console.WriteLine("Upcoming events:");
            if (events.Items == null || events.Items.Count == 0)
            {
                Console.WriteLine("No upcoming events found.");
                return;
            }
            foreach (var eventItem in events.Items)
            {
                var calenderevent = new calenderEvent();

                calenderevent.Organizer = eventItem.Organizer.Email;
                calenderevent.Summary = eventItem.Summary;
                calenderevent.StartTime = eventItem.Start.DateTime.ToString();
                calenderevent.EndTime = eventItem.End.DateTime.ToString();
                calenderevent.Description = eventItem.Description;
                GoogleEvents.Add(calenderevent);

            }
        }

    }
}

Controllers/BuscaController.cs
using HeathCheck1.Database;
using HeathCheck1.Models;
using HeathCheck1.Repositorios;
using Microsoft.AspNetCore.Mvc;

namespace HeathCheck1.Controllers
{
    public class BuscaController : Controller
    {
        private readonly IEspecialistaRepositorio _especialistaRepositorio;


        private readonly Context _bancocontext;


        public BuscaController(IEspecialistaRepositorio especialistaRepositorio, Context context)
        {
            _especialistaRepositorio = especialistaRepositorio;

            _bancocontext = context;

        }
        public IActionResult BuscaEspecialista()
        {
            
            return View();

            
        }
        public IActionResult TelaEspecialista()
        {

            return View();


        }

        public IActionResult ListarEspecialista(string searchstring)
        {

            var especialista = from m in _bancocontext.especialistas
                               select m;

            if (!String.IsNullOrEmpty(searchstring))
            {
                especialista = especialista.Where(s => s.name.Contains(searchstring));
            }

            return View(especialista);
        }
    }
}

Views/Shared/Components/MenuEspecialista/Default.cshtml
@model EspecialistaModel


                <a class="navbar-brand fs-1" asp-area="" asp-controller="Busca" asp-action="TelaEspecialista">Olá,@Model.name</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 fs-5">                       
                      
                          <li class="nav-item">
                            <a class="nav-link text-white" >Exames</a>
                        </li>
                     
                       
                        <li class="nav-item">
                            <a class="nav-link text-white" >Perguntas dos pacientes </a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav flex-grow-1 fs-5 justify-content-md-end">  
                         <li class="nav-item dropdown ">
                              <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Minha Conta
                              </a>  
                              <ul class="dropdown-menu dropdown-menu-dark  fs-5" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="LoginEspecialista" asp-action="Sair">Sair</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Agendamento" asp-action="Salvar">Ver minha agenda</a></li>
                               </ul>
                        </li>
                    </ul>
                </div>